apiVersion: v1
kind: Service
metadata:
  name: {{ include "gsf.fullname" . }}
  labels:
    {{- include "gsf.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8765
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gsf.selectorLabels" . | nindent 4 }}
